Impostos = {
    1: "Imposto sobre a importação de produtos estrangeiros (II)",
    2: "Imposto sobre a exportação de produtos nacionais ou nacionalizados (IE)",
    3: "Imposto sobre a renda e proventos de qualquer natureza (IR)",
    4: "Imposto sobre Produtos Industrializados (IPI)",
    5: "Imposto sobre Operações de Crédito, Câmbio e Seguro ou relativas a Títulos ou Valores Mobiliários (IOF)",
    6: "Imposto Territorial Rural (ITR)",
    7: "Imposto sobre operações relativas à Circulação de Mercadorias e prestação de Serviços de transporte interestadual, intermunicipal e de comunicação (ICMS)",
    8: "Imposto sobre Propriedade de Veículos Automotores (IPVA)",
    9: "Imposto sobre Transmissões Causa Mortis e Doações de Qualquer Bem ou Direito (ITCMd) - https://bit.ly/2T5anpt, !IMPOSTO FEUDAL! - Dica do @AthurLuiz",
    10: "Imposto sobre a Propriedade predial e Territorial Urbana (IPTU)",
    11: "Imposto sobre Transmissão inter vivos de Bens e Imóveis e de direitos reais a eles relativos (ITBI)",
    12: "Impostos sobre Serviços de Qualquer Natureza (ISS ou ISSQN).",
    13: "Taxa de Autorização do Trabalho Estrangeiro",
    14: "Taxa de Avaliação in loco das Instituições de Educação e Cursos de Graduação – Lei 10.870/2004",
    15: "Taxa de Avaliação da Conformidade – Lei 12.545/2011 – art. 13",
    16: "Taxa de Classificação, Inspeção e Fiscalização de produtos animais e vegetais ou de consumo nas atividades agropecuárias – Decreto-Lei 1.899/1981",
    17: "Taxa de Coleta de Lixo",
    18: "Taxa de Combate a Incêndios",
    19: "Taxa de Conservação e Limpeza Pública",
    20: "Taxa de Controle Administrativo de Incentivos Fiscais – TCIF – Lei 13.451/2017",
    21: "Taxa de Controle e Fiscalização Ambiental – TCFA – Lei 10.165/2000",
    22: "Taxa de Controle e Fiscalização de Produtos Químicos – Lei 10.357/2001, art. 16",
    23: "Taxa de Emissão de Documentos(níveis municipais, estaduais e federais)",
    24: "Taxa de Fiscalização da Aviação Civil – TFAC – Lei 11.292/2006",
    25: "Taxa de Fiscalização da Agência Nacional de Águas – ANA",
    26: "Taxa de Fiscalização do Mercado de Valores Mobiliários da CVM – Lei 7.940/1989",
    27: "Taxa de Fiscalização de Sorteios, Brindes ou Concursos – art. 50 da MP 2.158-35/2001",
    28: "Taxa de Fiscalização de Vigilância Sanitária – Lei 9.782/1999, art. 23",
    29: "Taxa de Fiscalização dos Produtos Controlados pelo Exército Brasileiro – TFPC – Lei 10.834/2003",
    30: "Taxa de Fiscalização dos Mercados de Seguro e Resseguro, de Capitalização e de Previdência Complementar Aberta – art. 48 a 59 da Lei 12.249/2010",
    31: "Taxa de Fiscalização e Controle da Previdência Complementar – TAFIC – Entidades Fechadas de Previdência Complementar – art. 12 da Lei 12.154/2009",
    32: "Taxa de Licenciamento Anual de Veículo – art. 130 da Lei 9.503/1997",
    33: "Taxa de Licenciamento, Controle e Fiscalização de Materiais Nucleares e Radioativos e suas instalações",
    34: "Taxa de Licenciamento para Funcionamento e Alvará Municipal",
    35: "Taxa de Pesquisa Mineral DNPM",
    36: "Taxa de Serviços Administrativos(TSA) – Zona Franca de Manaus –  Lei 13.451/2017",
    37: "Taxa de Serviços Metrológicos – art. 11 da Lei 9.933/1999",
    38: "Taxa de Utilização de Selo de Controle – art. 13 da Lei 12.995/2014",
    39: "Taxas ao Conselho Nacional de Petróleo(CNP)",
    40: "Taxa de Outorgas(Radiodifusão, Telecomunicações, Transporte Rodoviário e Ferroviário, etc.)",
    41: "Taxas de Saúde Suplementar – ANS  – Lei 9.961/2000, art. 18",
    42: "Taxa de Utilização do SISCOMEX",
    43: "Taxa de Utilização do MERCANTE",
    44: "Taxas do Registro do Comércio(Juntas Comerciais)",
    45: "Taxas Judiciárias",
    46: "Taxas Processuais do Conselho Administrativo de Defesa Econômica – CADE – art. 23 da Lei 12.529/2011",
    47: "Fundo Especial de Desenvolvimento e Aperfeiçoamento das Atividades de Fiscalização(Fundaf)",
    48: " Contribuições trabalhistas ou sobre a folha de pagamento",
    49: "PIS/PASEP",
    50: "Contribuição Social para o Financiamento da Seguridade Social(COFINS)",
    51: "Contribuição Social sobre o Lucro Líquido(CSLL)",
    52: "Contribuições sobre as importações",
    53: "Contribuição Social para o Financiamento da Seguridade Social(COFINS)",
    54: "Programa de Integração Social(PIS)",
    55: "Fundo de Universalização dos Serviços de Telecomunicações(FUST)",
    56: "Contribuição ao Serviço Brasileiro de Apoio às Micro e Pequenas Empresas(Sebrae) – Lei 8.029/1990",
    57: "Contribuição ao Serviço Nacional de Aprendizagem Comercial(SENAC) – Lei 8.621/1946",
    58: "Contribuição ao Serviço Nacional de Aprendizagem do Transporte(SENAT) – Lei 8.706/1993",
    59: "Contribuição ao Serviço Nacional de Aprendizagem Industrial(SENAI) – Lei 4.048/1942",
    60: "Contribuição ao Serviço Nacional de Aprendizagem Rural(SENAR) – Lei 8.315/1991",
    61: "Contribuição ao Serviço Nacional de Aprendizagem do Cooperativismo(Sescoop)",
    62: "Contribuição ao Serviço Social da Indústria(SESI) – Lei 9.403/1946",
    63: "Contribuição ao Serviço Social do Comércio(SESC) – Lei 9.853/1946",
    64: "Contribuição ao Serviço Social do Cooperativismo(SESCOOP)",
    65: "Contribuição ao Serviço Social do Transporte(SEST) – Lei 8.706/1993",
    66: "Contribuições aos Órgãos de Fiscalização Profissional(OAB, CRC, CREA, CRECI, CORE, etc.)",
    67: "Contribuição à Direção de Portos e Costas(DPC)",
    68: "Contribuição ao Fundo Nacional de Desenvolvimento Científico e Tecnológico(FNDCT) – Lei 10.168/2000",
    69: "Contribuição ao Fundo Nacional de Desenvolvimento da Educação(FNDE)",
    70: "Contribuição ao Funrural",
    71: "Contribuição ao Instituto Nacional de Colonização e Reforma Agrária(INCRA) – Lei 2.613/1955",
    72: "Contribuição ao Seguro Acidente de Trabalho(SAT)",
    73: "Contribuição Confederativa Laboral",
    74: "Contribuição Confederativa Patronal",
    75: "Contribuição de Intervenção do Domínio Econômico(CIDE – Combustíveis) – Lei 10.336/2001",
    76: "Contribuição de Intervenção do Domínio Econômico – CIDE Remessas Exterior – Lei 10.168/2000",
    77: "Contribuição para a Assistência Social e Educacional aos Atletas Profissionais – FAAP",
    78: "Contribuição para o Fomento da Radiodifusão Pública – art. 32 da Lei 11.652/2008",
    79: "Contribuição Previdenciária sobre a Receita Bruta(CPRB) – art. 8º da Lei 12.546/2011",
    80: "Contribuição para Custeio do Serviço de Iluminação Pública – Emenda Constitucional 39/2002",
    81: "Contribuição para o Desenvolvimento da Indústria Cinematográfica Nacional(CONDECINE)",
    82: "Contribuição Sindical Laboral",
    83: "Contribuição Sindical Patronal",
    84: "Contribuição Social Adicional para Reposição das Perdas Inflacionárias do FGTS – Lei complementar 110/2001",
    85: "Fundo Aeroviário(FAER)",
    86: "Fundo de Combate à Pobreza",
    87: "Fundo Estadual de Equilíbrio Fiscal – FEEF",
    88: "Fundo de Fiscalização das Telecomunicações(FISTEL)",
    89: "Fundo de Garantia por Tempo de Serviço(FGTS)",
}